### ISSUE TITLE
ImpossibleSearchException:No registered extension is able to read content of type text/html

### ISSUE THREAD

**Issue by vtortola** [Terradue/DotNetOpenSearch#8]
Hi,

I want to execute this query: http://en.wikipedia.org/w/api.php?action=opensearch&search=mariano&namespace=0&format=xml  from .NET, but I am getting an exception when using this code at the second line:

```csharp
var engine = new OpenSearchEngine();
var entity = new GenericOpenSearchable(new OpenSearchUrl("http://en.wikipedia.org/w/api.php"), engine);
 
var parameters = new NameValueCollection();
parameters.Add("action", "opensearch");
parameters.Add("search", "mariano");
parameters.Add("namespace", "0");
parameters.Add("format", "xml");

var result = engine.Query(entity, parameters, "Atom");
```

Exception:

```
Terradue.OpenSearch.ImpossibleSearchException was caught
  HResult=-2146233088
  Message=No registered extension is able to read content of type text/html
  Source=Terradue.OpenSearch
  StackTrace:
       at Terradue.OpenSearch.Engine.OpenSearchEngine.AutoDiscoverFromQueryUrl(OpenSearchUrl url)
       at Terradue.OpenSearch.GenericOpenSearchable..ctor(OpenSearchUrl url, OpenSearchEngine ose)
```       

Any idea what may be the problem?

Cheers.

**Comment by emmanuelmathot** [comment]
Hello,
The API exposed by wikipedia is not the same implemented by this library.
Indeed, Terradue.OpenSearch deals with OGC OpenSearch specification: http://en.wikipedia.org/wiki/OpenSearch, http://www.opensearch.org/Specifications/OpenSearch/1.1
I don't know exactly to which specification refers the wikipedia API.
What do you intend to do? Using Wikipedia API or using OGC OpenSearch?

**Comment by vtortola** [comment]
I see. I wanted to use the Wikimedia API to do searches in Wikipedia, and I thought it was the same "opensearch" specification.
